name: CI

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace homepage
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "\"homepage\": \"https://fribbels.github.io/hsr-optimizer\""
          replace: "\"homepage\": \"https://fribbels.github.io/beta-hsr-optimizer\""
          include: "package.json"
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'fribbels'
          destination-repository-name: 'beta-hsr-optimizer'
          target-branch: main
